"""Ahead-of-time compiler: Emdashy -> a standalone Python script.

The output embeds the decoded program and a self-contained runtime with
the exact semantics of the reference interpreter (bignums included) and
no dependency on the emdashy package.
"""

from __future__ import annotations

from typing import List

from . import __version__
from .parser import Program

_RUNTIME = '''
def main() -> int:
    stack, calls, heap = [], [], {}
    pending = []

    def die(msg):
        sys.stdout.flush()
        sys.stderr.write("emdashy: runtime error: %s\\n" % msg)
        raise SystemExit(1)

    def pop():
        if not stack:
            die("stack underflow")
        return stack.pop()

    def peek(depth):
        if len(stack) <= depth:
            die("stack underflow")
        return stack[-1 - depth]

    def read1():
        return pending.pop() if pending else sys.stdin.read(1)

    def read_int():
        ch = read1()
        while ch and ch.isspace():
            ch = read1()
        if not ch:
            die("unexpected end of input while reading an integer")
        sign = 1
        if ch in "+-":
            sign = -1 if ch == "-" else 1
            ch = read1()
        digits = ""
        while ch and ch.isdigit():
            digits += ch
            ch = read1()
        if ch:
            pending.append(ch)
        if not digits:
            die("invalid integer on input")
        return sign * int(digits)

    pc, n = 0, len(INSTRS)
    while 0 <= pc < n:
        op, arg = INSTRS[pc]
        pc += 1
        if op == "push":
            stack.append(arg)
        elif op == "pop":
            pop()
        elif op == "dup":
            stack.append(peek(0))
        elif op == "swap":
            b, a = pop(), pop()
            stack.append(b)
            stack.append(a)
        elif op == "over":
            stack.append(peek(1))
        elif op == "add":
            b, a = pop(), pop()
            stack.append(a + b)
        elif op == "sub":
            b, a = pop(), pop()
            stack.append(a - b)
        elif op == "mul":
            b, a = pop(), pop()
            stack.append(a * b)
        elif op == "div":
            b, a = pop(), pop()
            if b == 0:
                die("division by zero")
            stack.append(a // b)
        elif op == "mod":
            b, a = pop(), pop()
            if b == 0:
                die("division by zero")
            stack.append(a % b)
        elif op == "neg":
            stack.append(-pop())
        elif op == "eq":
            b, a = pop(), pop()
            stack.append(1 if a == b else 0)
        elif op == "lt":
            b, a = pop(), pop()
            stack.append(1 if a < b else 0)
        elif op == "gt":
            b, a = pop(), pop()
            stack.append(1 if a > b else 0)
        elif op == "label":
            pass
        elif op == "jmp":
            pc = LABELS[arg]
        elif op == "jz":
            if pop() == 0:
                pc = LABELS[arg]
        elif op == "jnz":
            if pop() != 0:
                pc = LABELS[arg]
        elif op == "call":
            calls.append(pc)
            pc = LABELS[arg]
        elif op == "ret":
            if not calls:
                die("'ret' outside of a call")
            pc = calls.pop()
        elif op == "load":
            stack.append(heap.get(pop(), 0))
        elif op == "store":
            v = pop()
            heap[pop()] = v
        elif op == "outn":
            sys.stdout.write(str(pop()))
        elif op == "outc":
            v = pop()
            if not (0 <= v <= 0x10FFFF) or 0xD800 <= v <= 0xDFFF:
                die("%d is not a valid character code" % v)
            sys.stdout.write(chr(v))
        elif op == "inn":
            stack.append(read_int())
        elif op == "inc":
            ch = read1()
            stack.append(ord(ch) if ch else -1)
        elif op == "halt":
            break
    sys.stdout.flush()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def compile_to_python(program: Program) -> str:
    lines: List[str] = [
        "#!/usr/bin/env python3",
        f'"""Generated by emdash compile v{__version__} from {program.source}."""',
        "",
        "import sys",
        "",
        "INSTRS = [",
    ]
    for instr in program.instrs:
        lines.append(f"    ({instr.name!r}, {instr.arg!r}),")
    lines.append("]")
    labels = ", ".join(f"{k}: {v}" for k, v in sorted(program.labels.items()))
    lines.append(f"LABELS = {{{labels}}}")
    lines.append(_RUNTIME)
    return "\n".join(lines)
