"""Ahead-of-time compiler: Emdashy -> portable C99.

Each label becomes a real C label and each branch a ``goto``, so the
generated code has no dispatch loop at all.  ``call``/``ret`` use a
return-id stack plus a dispatcher ``switch``.

Semantic notes versus the reference interpreter (documented in SPEC.md):

* integers are 64-bit two's complement (the interpreter has bignums);
* ``inc`` reads one *byte* (the interpreter reads one character);
* everything else — floor division, sign-of-divisor modulo, UTF-8
  output, the sparse heap — matches exactly.
"""

from __future__ import annotations

from typing import List

from . import __version__, ops
from .parser import Program

_PRELUDE = r"""#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <inttypes.h>

#define STACK_MAX (1u << 20)
#define CALL_MAX  (1u << 16)

static int64_t st[STACK_MAX];
static size_t sp;
static uint32_t rs[CALL_MAX];
static size_t rp;

static void die(const char *msg) {
    fflush(stdout);
    fprintf(stderr, "emdashy: runtime error: %s\n", msg);
    exit(1);
}

static void push(int64_t v) {
    if (sp >= STACK_MAX) die("stack overflow");
    st[sp++] = v;
}

static int64_t pop(void) {
    if (sp == 0) die("stack underflow");
    return st[--sp];
}

static int64_t peek(size_t depth) {
    if (sp <= depth) die("stack underflow");
    return st[sp - 1 - depth];
}

static int64_t fdiv64(int64_t a, int64_t b) {
    int64_t q;
    if (b == 0) die("division by zero");
    q = a / b;
    if ((a % b != 0) && ((a < 0) != (b < 0))) q--;
    return q;
}

static int64_t fmod64(int64_t a, int64_t b) {
    int64_t r;
    if (b == 0) die("division by zero");
    r = a % b;
    if (r != 0 && ((r < 0) != (b < 0))) r += b;
    return r;
}

/* Sparse heap: an open-addressing hash map from int64 to int64. */
typedef struct { int64_t key, val; unsigned char used; } Cell;
static Cell *hcells;
static size_t hcap, hcount;

static size_t hslot(int64_t key) {
    uint64_t h = (uint64_t)key * 11400714819323198485ULL;
    size_t i = (size_t)(h & (hcap - 1));
    while (hcells[i].used && hcells[i].key != key)
        i = (i + 1) & (hcap - 1);
    return i;
}

static void hgrow(void) {
    size_t oldcap = hcap, i;
    Cell *old = hcells;
    hcap = hcap ? hcap * 2 : 1024;
    hcells = calloc(hcap, sizeof(Cell));
    if (!hcells) die("out of memory");
    for (i = 0; i < oldcap; i++)
        if (old[i].used)
            hcells[hslot(old[i].key)] = old[i];
    free(old);
}

static void hset(int64_t key, int64_t val) {
    size_t i;
    if (hcount * 10 >= hcap * 7) hgrow();
    i = hslot(key);
    if (!hcells[i].used) {
        hcells[i].used = 1;
        hcells[i].key = key;
        hcount++;
    }
    hcells[i].val = val;
}

static int64_t hget(int64_t key) {
    size_t i;
    if (hcap == 0) return 0;
    i = hslot(key);
    return hcells[i].used ? hcells[i].val : 0;
}

static void out_char(int64_t c) {
    uint32_t u;
    if (c < 0 || c > 0x10FFFF || (c >= 0xD800 && c <= 0xDFFF))
        die("invalid character code");
    u = (uint32_t)c;
    if (u < 0x80) {
        putchar((int)u);
    } else if (u < 0x800) {
        putchar(0xC0 | (u >> 6));
        putchar(0x80 | (u & 0x3F));
    } else if (u < 0x10000) {
        putchar(0xE0 | (u >> 12));
        putchar(0x80 | ((u >> 6) & 0x3F));
        putchar(0x80 | (u & 0x3F));
    } else {
        putchar(0xF0 | (u >> 18));
        putchar(0x80 | ((u >> 12) & 0x3F));
        putchar(0x80 | ((u >> 6) & 0x3F));
        putchar(0x80 | (u & 0x3F));
    }
}

static int64_t in_num(void) {
    long long v;
    fflush(stdout);
    if (scanf("%lld", &v) != 1) die("expected an integer on stdin");
    return (int64_t)v;
}
"""

_SIMPLE = {
    "pop": "(void)pop();",
    "dup": "push(peek(0));",
    "over": "push(peek(1));",
    "neg": "push(-pop());",
    "ret": "goto ret_dispatch;",
    "load": "push(hget(pop()));",
    "outc": "out_char(pop());",
    "inn": "push(in_num());",
    "halt": "goto program_end;",
}

_BINOPS = {
    "add": "push(a + b);",
    "sub": "push(a - b);",
    "mul": "push(a * b);",
    "div": "push(fdiv64(a, b));",
    "mod": "push(fmod64(a, b));",
    "eq": "push(a == b ? 1 : 0);",
    "lt": "push(a < b ? 1 : 0);",
    "gt": "push(a > b ? 1 : 0);",
}


def compile_to_c(program: Program) -> str:
    lines: List[str] = [
        f"/* Generated by emdash compile v{__version__} from {program.source} */",
        _PRELUDE,
        "int main(void) {",
    ]
    body: List[str] = []
    ret_ids = 0

    for instr in program.instrs:
        name, arg = instr.name, instr.arg
        loc = f"/* {instr.render()} */"
        if name == "push":
            body.append(f"    push(INT64_C({arg})); {loc}")
        elif name in _BINOPS:
            body.append(f"    {{ int64_t b = pop(), a = pop(); {_BINOPS[name]} }} {loc}")
        elif name == "swap":
            body.append(f"    {{ int64_t b = pop(), a = pop(); push(b); push(a); }} {loc}")
        elif name == "label":
            body.append(f"L{arg}:; {loc}")
        elif name == "jmp":
            body.append(f"    goto L{arg}; {loc}")
        elif name == "jz":
            body.append(f"    if (pop() == 0) goto L{arg}; {loc}")
        elif name == "jnz":
            body.append(f"    if (pop() != 0) goto L{arg}; {loc}")
        elif name == "call":
            ret_ids += 1
            body.append(f"    if (rp >= CALL_MAX) die(\"call stack overflow\"); {loc}")
            body.append(f"    rs[rp++] = {ret_ids}; goto L{arg};")
            body.append(f"ret_{ret_ids}:;")
        elif name == "store":
            body.append(f"    {{ int64_t v = pop(), a = pop(); hset(a, v); }} {loc}")
        elif name == "outn":
            body.append(f"    printf(\"%\" PRId64, pop()); {loc}")
        elif name == "inc":
            body.append(f"    {{ int ch = getchar(); push(ch == EOF ? -1 : ch); }} {loc}")
        elif name in _SIMPLE:
            body.append(f"    {_SIMPLE[name]} {loc}")
        else:  # pragma: no cover - the parser only produces known ops
            raise ValueError(f"cannot compile instruction '{name}'")

    lines.extend(body)
    lines.append("    goto program_end;")
    lines.append("")
    lines.append("ret_dispatch:")
    lines.append("    if (rp == 0) die(\"'ret' outside of a call\");")
    lines.append("    switch (rs[--rp]) {")
    for k in range(1, ret_ids + 1):
        lines.append(f"    case {k}: goto ret_{k};")
    lines.append("    }")
    lines.append("    die(\"corrupt call stack\");")
    lines.append("")
    lines.append("program_end:")
    lines.append("    fflush(stdout);")
    lines.append("    return 0;")
    lines.append("}")
    return "\n".join(lines) + "\n"
